// Ship sprites - Side view pixel art ships
import { W, D, H, S, M, R, _ } from "./colors.js";

// Cutter - Small single-mast ship (16x14)
export const CUTTER = [
    [_, _, _, _, _, _, _, _, M, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _, M, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, S, M, S, _, _, _, _, _, _],
    [_, _, _, _, _, _, S, S, M, S, S, _, _, _, _, _],
    [_, _, _, _, _, S, S, S, M, S, S, S, _, _, _, _],
    [_, _, _, _, S, S, S, S, M, S, S, S, S, _, _, _],
    [_, _, _, _, S, S, S, S, M, S, S, S, S, _, _, _],
    [_, _, _, _, _, _, _, _, M, _, _, _, _, _, _, _],
    [_, _, _, D, D, D, D, D, D, D, D, D, D, _, _, _],
    [_, _, D, W, W, W, W, W, W, W, W, W, W, D, _, _],
    [_, D, W, W, W, W, W, W, W, W, W, W, W, W, D, _],
    [_, H, H, H, H, H, H, H, H, H, H, H, H, H, H, _],
    [_, _, H, H, H, H, H, H, H, H, H, H, H, H, _, _],
    [_, _, _, _, H, H, H, H, H, H, H, H, _, _, _, _],
];

// Schooner - Two-mast balanced ship (20x16)
export const SCHOONER = [
    [_, _, _, _, _, _, M, _, _, _, _, _, M, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, M, _, _, _, _, _, M, _, _, _, _, _, _, _],
    [_, _, _, _, _, S, M, S, _, _, _, S, M, S, _, _, _, _, _, _],
    [_, _, _, _, S, S, M, S, S, _, S, S, M, S, S, _, _, _, _, _],
    [_, _, _, S, S, S, M, S, S, S, S, S, M, S, S, S, _, _, _, _],
    [_, _, _, S, S, S, M, S, S, S, S, S, M, S, S, S, _, _, _, _],
    [_, _, _, S, S, S, M, S, S, S, S, S, M, S, S, S, _, _, _, _],
    [_, _, _, _, S, S, M, S, S, _, S, S, M, S, S, _, _, _, _, _],
    [_, _, _, _, _, _, M, _, _, _, _, _, M, _, _, _, _, _, _, _],
    [_, _, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, _, _],
    [_, D, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, D, _],
    [D, W, W, W, R, W, W, W, W, W, W, W, W, W, W, R, W, W, W, D],
    [H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H],
    [_, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, _],
    [_, _, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, _, _],
    [_, _, _, _, _, H, H, H, H, H, H, H, H, H, H, _, _, _, _, _],
];

// Brigantine - Fast two-mast trader (24x18)
export const BRIGANTINE = [
    [_, _, _, _, _, _, _, M, _, _, _, _, _, _, _, _, M, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, M, _, _, _, _, _, _, _, _, M, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, S, M, S, _, _, _, _, _, _, S, M, S, _, _, _, _, _, _],
    [_, _, _, _, _, S, S, M, S, S, _, _, _, _, S, S, M, S, S, _, _, _, _, _],
    [_, _, _, _, S, S, S, M, S, S, S, _, _, S, S, S, M, S, S, S, _, _, _, _],
    [_, _, _, S, S, S, S, M, S, S, S, S, S, S, S, S, M, S, S, S, S, _, _, _],
    [_, _, _, S, S, S, S, M, S, S, S, S, S, S, S, S, M, S, S, S, S, _, _, _],
    [_, _, _, S, S, S, S, M, S, S, S, S, S, S, S, S, M, S, S, S, S, _, _, _],
    [_, _, _, _, S, S, S, M, S, S, S, _, _, S, S, S, M, S, S, S, _, _, _, _],
    [_, _, _, _, _, _, _, M, _, _, _, _, _, _, _, _, M, _, _, _, _, _, _, _],
    [_, _, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, _, _],
    [_, D, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, D, _],
    [D, W, W, W, R, W, W, W, W, W, W, W, W, W, W, W, W, W, W, R, W, W, W, D],
    [D, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, D],
    [H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H],
    [_, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, _],
    [_, _, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, _, _],
    [_, _, _, _, _, _, H, H, H, H, H, H, H, H, H, H, H, H, _, _, _, _, _, _],
];

// Galleon - Massive three-mast cargo ship (30x22)
export const GALLEON = [
    [_, _, _, _, _, _, _, _, _, M, _, _, _, _, _, _, _, _, _, M, _, _, _, _, _, _, _, M, _, _],
    [_, _, _, _, _, _, _, _, _, M, _, _, _, _, _, _, _, _, _, M, _, _, _, _, _, _, _, M, _, _],
    [_, _, _, _, _, _, _, _, S, M, S, _, _, _, _, _, _, _, S, M, S, _, _, _, _, _, S, M, S, _],
    [_, _, _, _, _, _, _, S, S, M, S, S, _, _, _, _, _, S, S, M, S, S, _, _, _, S, S, M, S, S],
    [_, _, _, _, _, _, S, S, S, M, S, S, S, _, _, _, S, S, S, M, S, S, S, _, S, S, S, M, S, S],
    [_, _, _, _, _, S, S, S, S, M, S, S, S, S, _, S, S, S, S, M, S, S, S, S, S, S, S, M, S, S],
    [_, _, _, _, S, S, S, S, S, M, S, S, S, S, S, S, S, S, S, M, S, S, S, S, S, S, S, M, S, _],
    [_, _, _, _, S, S, S, S, S, M, S, S, S, S, S, S, S, S, S, M, S, S, S, S, S, S, S, M, _, _],
    [_, _, _, _, S, S, S, S, S, M, S, S, S, S, S, S, S, S, S, M, S, S, S, S, S, S, S, M, _, _],
    [_, _, _, _, _, S, S, S, S, M, S, S, S, S, _, S, S, S, S, M, S, S, S, _, _, S, S, M, _, _],
    [_, _, _, _, _, _, _, _, _, M, _, _, _, _, _, _, _, _, _, M, _, _, _, _, _, _, _, M, _, _],
    [_, _, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, _],
    [_, D, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, D],
    [D, W, W, W, R, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, R, W, W, D],
    [D, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, D],
    [D, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, W, D],
    [H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H],
    [H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H],
    [_, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, _],
    [_, _, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, _, _],
    [_, _, _, _, _, _, _, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _, _, _, H, H, H, H, H, H, H, H, H, H, _, _, _, _, _, _, _, _, _, _],
];

// Ship metadata
export const SHIPS = {
    cutter: {
        name: "Cutter",
        sprite: CUTTER,
        build_time: 5,
        speed: 2,
        cargo: 2,
        combat: 1,
        sight_distance: 1,
        cost: { wood: 10, food: 5 },
        description: "Small, scrappy starter",
    },
    schooner: {
        name: "Schooner",
        sprite: SCHOONER,
        build_time: 10,
        speed: 1.5,
        cargo: 4,
        combat: 2,
        sight_distance: 1,
        cost: { wood: 25, food: 10 },
        description: "Balanced workhorse",
    },
    brigantine: {
        name: "Brigantine",
        sprite: BRIGANTINE,
        build_time: 25,
        speed: 2.5,
        cargo: 6,
        combat: 3,
        sight_distance: 2,
        cost: { wood: 50, food: 20 },
        description: "Fast, medium cargo",
    },
    galleon: {
        name: "Galleon",
        sprite: GALLEON,
        build_time: 50,
        speed: 1,
        cargo: 12,
        combat: 4,
        sight_distance: 3,
        cost: { wood: 100, food: 75 },
        description: "Massive cargo hauler",
    },
};
